export interface PlaybookUseCase {
  id: string
  title: string
  problem: string
  solution: string
  tools: string[]
  monthlyValue: string
  difficulty: "Easy" | "Medium" | "Advanced"
  timeToDeliver: string
  pitchLine: string
}

export interface IndustryPlaybook {
  id: string
  industry: string
  emoji: string
  description: string
  avgDealSize: string
  topPain: string
  useCases: PlaybookUseCase[]
}

export const PLAYBOOK_MANIFEST: IndustryPlaybook[] = [
  {
    id: "hvac",
    industry: "HVAC & Plumbing",
    emoji: "🔧",
    description: "High-ticket services, seasonal demand, and customers who need 24/7 emergency response.",
    avgDealSize: "$1,500–$3,500/mo",
    topPain: "Missing calls after hours and losing leads to faster competitors.",
    useCases: [
      {
        id: "hvac-ai-receptionist",
        title: "AI Receptionist + Booking Bot",
        problem: "Miss 40% of calls after 5pm and on weekends. Competitors answer — they book.",
        solution: "AI voice agent answers 24/7, qualifies the emergency vs. routine, books into their scheduling software.",
        tools: ["Vapi", "Make", "GoHighLevel (GHL)"],
        monthlyValue: "$800–$1,500/mo",
        difficulty: "Easy",
        timeToDeliver: "3–5 days",
        pitchLine: "You're losing an average of $X per missed after-hours call. I'll have an AI agent answering your phone 24/7 and booking appointments directly into your calendar by Friday — for less than the cost of a part-time receptionist.",
      },
      {
        id: "hvac-review-automation",
        title: "Automated Review Generation",
        problem: "Competitors have 200+ Google reviews. They have 15. Customers don't trust them.",
        solution: "After each job, SMS + email review request sent automatically. Negative feedback routed to owner, positive to Google.",
        tools: ["Make", "Twilio (SMS)", "Google Business API"],
        monthlyValue: "$400–$600/mo",
        difficulty: "Easy",
        timeToDeliver: "1–2 days",
        pitchLine: "Your competitor has 10x your Google reviews. I can automate that process and change this within 90 days.",
      },
      {
        id: "hvac-seasonal-reactivation",
        title: "Seasonal Customer Reactivation",
        problem: "They have 500 past customers they've never followed up with for annual maintenance.",
        solution: "AI-generated seasonal campaign: SMS + email blast with personalized timing (last service date), offer a tune-up.",
        tools: ["Instantly", "Clay", "Claude", "Google Sheets"],
        monthlyValue: "$600/mo",
        difficulty: "Medium",
        timeToDeliver: "5–7 days",
        pitchLine: "You have 500 past customers who haven't heard from you in 2 years. Let's fix that this week.",
      },
    ],
  },
  {
    id: "dental",
    industry: "Dental Offices",
    emoji: "🦷",
    description: "High LTV patients, appointment-heavy operations, and insurance paperwork.",
    avgDealSize: "$1,200–$2,500/mo",
    topPain: "No-shows, insurance follow-ups, and front desk overwhelm.",
    useCases: [
      {
        id: "dental-noshow-reduction",
        title: "No-Show Reduction System",
        problem: "15–25% no-show rate. Each empty chair costs $300–$800 of lost revenue.",
        solution: "Automated SMS/email reminders at 72h, 24h, and 2h before appointment. Easy one-tap confirm/reschedule.",
        tools: ["Make", "Twilio", "GoHighLevel (GHL)"],
        monthlyValue: "$800–$1,200/mo",
        difficulty: "Easy",
        timeToDeliver: "3–5 days",
        pitchLine: "At $400 per empty chair, your 20% no-show rate is costing you $X per month. I can cut that in half with automated SMS reminders that take 3 days to set up.",
      },
      {
        id: "dental-insurance-followup",
        title: "Insurance Claim Follow-Up Bot",
        problem: "Staff spends 2–3 hours/day calling insurance companies to check claim status.",
        solution: "AI workflow checks claim status via portal scraping, surfaces pending claims, drafts follow-up letters.",
        tools: ["n8n", "Claude", "Google Sheets"],
        monthlyValue: "$1,000–$1,500/mo",
        difficulty: "Advanced",
        timeToDeliver: "2–3 weeks",
        pitchLine: "Your front desk is spending 3 hours a day on hold with insurance. That's $X/month in labor I can automate.",
      },
      {
        id: "dental-patient-reactivation",
        title: "Lapsed Patient Reactivation",
        problem: "Hundreds of patients who haven't been in for 18+ months. Not following up.",
        solution: "Segment by last visit date, run AI-personalized email + SMS campaign to re-book cleanings.",
        tools: ["Instantly", "Clay", "Claude", "CSV export from their system"],
        monthlyValue: "$600–$800/mo",
        difficulty: "Easy",
        timeToDeliver: "5–7 days",
        pitchLine: "You have 300 patients you haven't seen in 2 years. A single campaign to them could fill your calendar for 3 months.",
      },
    ],
  },
  {
    id: "real-estate",
    industry: "Real Estate Agents",
    emoji: "🏠",
    description: "Commission-heavy, relationship-driven, and terrible at systematic follow-up.",
    avgDealSize: "$1,500–$4,000/mo",
    topPain: "Leads go cold because they can't follow up fast enough.",
    useCases: [
      {
        id: "re-instant-lead-response",
        title: "Instant Lead Response System",
        problem: "Internet leads go cold within 5 minutes if not contacted. Agents respond in 6+ hours.",
        solution: "AI agent responds to Zillow/Realtor.com leads within 60 seconds, qualifies buyer/seller, books a showing.",
        tools: ["Vapi", "n8n", "GoHighLevel (GHL)"],
        monthlyValue: "$1,500–$3,000/mo",
        difficulty: "Medium",
        timeToDeliver: "1–2 weeks",
        pitchLine: "You're paying $500/month for Zillow leads and responding in 6 hours. Internet leads go cold in 5 minutes — your AI agent will respond in under 60 seconds and qualify the buyer before you even wake up.",
      },
      {
        id: "re-past-client-nurture",
        title: "Past Client Referral Engine",
        problem: "80% of buyers say they'd use the same agent again — but only 12% do, because agents don't stay top of mind.",
        solution: "Monthly AI-personalized touchpoint: market update, home anniversary, neighborhood news. Referral ask at 6-month mark.",
        tools: ["Instantly", "Clay", "Claude", "Google Sheets"],
        monthlyValue: "$800–$1,200/mo",
        difficulty: "Easy",
        timeToDeliver: "5–7 days",
        pitchLine: "You have 200 past clients who love you. The problem is you're not in front of them — your competitor is.",
      },
    ],
  },
  {
    id: "restaurants",
    industry: "Restaurants & Food Service",
    emoji: "🍕",
    description: "Thin margins, high labor costs, and customers who live on social media.",
    avgDealSize: "$500–$1,200/mo",
    topPain: "Empty tables on slow nights and no system for repeat business.",
    useCases: [
      {
        id: "restaurant-reactivation",
        title: "'We Miss You' Reactivation Campaign",
        problem: "They have 2,000 emails from online orders but have never sent a single promotional message.",
        solution: "Segment by last order date, send AI-crafted 'we miss you' offer with SMS + email. A/B test the offer.",
        tools: ["Instantly", "Clay", "Claude", "CSV export"],
        monthlyValue: "$400–$600/mo",
        difficulty: "Easy",
        timeToDeliver: "3–5 days",
        pitchLine: "You have 2,000 people who've already eaten here and given you their email. One campaign to them is $X in revenue.",
      },
      {
        id: "restaurant-review-ai",
        title: "AI Review Response + Generation",
        problem: "Owner spends 30 min/day responding to Google reviews, often poorly. Negative reviews go unanswered.",
        solution: "AI drafts responses to every review in their brand voice. Positive experience triggers automated review request.",
        tools: ["Claude", "Make", "Google Business API"],
        monthlyValue: "$300–$500/mo",
        difficulty: "Easy",
        timeToDeliver: "2–3 days",
        pitchLine: "I'll save you 30 minutes every day responding to reviews — and your responses will actually be good.",
      },
    ],
  },
  {
    id: "law-firms",
    industry: "Law Firms",
    emoji: "⚖️",
    description: "High-value clients, intake-heavy operations, and overwhelmed paralegals.",
    avgDealSize: "$2,000–$5,000/mo",
    topPain: "Slow intake process loses clients to faster competitors.",
    useCases: [
      {
        id: "law-intake-automation",
        title: "AI-Powered Client Intake",
        problem: "Intake forms take 3–5 days to process. Prospective clients call 3 firms — the first one to respond wins.",
        solution: "24/7 AI chat handles initial intake, qualifies the case type, books a consultation, and syncs to their case management system.",
        tools: ["n8n + Claude", "Make", "GoHighLevel (GHL)"],
        monthlyValue: "$2,000–$3,500/mo",
        difficulty: "Medium",
        timeToDeliver: "1–2 weeks",
        pitchLine: "Personal injury prospects call 3 firms and hire the first one that responds. Your intake takes 3–5 days. I'll have an AI agent qualifying cases and booking consultations 24/7 within 2 weeks.",
      },
      {
        id: "law-document-summarization",
        title: "AI Document Summarization",
        problem: "Paralegals spend 2–4 hours summarizing discovery documents, depositions, and contracts.",
        solution: "Claude-powered document pipeline: drop a PDF in, get a structured summary with key dates, parties, obligations.",
        tools: ["Claude API", "Make", "Google Drive"],
        monthlyValue: "$1,500–$2,500/mo",
        difficulty: "Medium",
        timeToDeliver: "1–2 weeks",
        pitchLine: "Your paralegals are spending $X/hour reading PDFs I can summarize in 30 seconds.",
      },
    ],
  },
  {
    id: "e-commerce",
    industry: "E-Commerce Brands",
    emoji: "🛒",
    description: "DTC brands with email lists, ad spend, and abandoned cart problems.",
    avgDealSize: "$1,000–$3,000/mo",
    topPain: "70% cart abandonment and no systematic win-back process.",
    useCases: [
      {
        id: "ecom-abandoned-cart",
        title: "AI-Personalized Abandoned Cart Recovery",
        problem: "Standard abandoned cart emails get 3–5% recovery. They're generic.",
        solution: "Claude-generated abandoned cart emails personalized to cart contents, browse history, and customer segment. 3-step sequence.",
        tools: ["Claude", "Make", "Klaviyo/Shopify"],
        monthlyValue: "$1,000–$2,000/mo",
        difficulty: "Medium",
        timeToDeliver: "1–2 weeks",
        pitchLine: "You're recovering 4% of abandoned carts. Personalized AI emails will push that to 10–15%.",
      },
      {
        id: "ecom-ai-product-descriptions",
        title: "AI Product Description Generator",
        problem: "They have 500 products with weak descriptions. No time to write them. SEO is suffering.",
        solution: "Claude batch-generates product descriptions at scale from CSV: title, category, key features → polished, SEO-optimized copy.",
        tools: ["Claude API", "Make", "Shopify API"],
        monthlyValue: "$800–$1,500/mo",
        difficulty: "Easy",
        timeToDeliver: "3–5 days",
        pitchLine: "Your 500 product pages are costing you Google traffic. I'll rewrite all of them in a week using AI.",
      },
    ],
  },
  {
    id: "roofing",
    industry: "Roofing & Contractors",
    emoji: "🏗️",
    description: "Storm-driven demand spikes, high-ticket projects, and slow follow-up kill revenue.",
    avgDealSize: "$2,000–$5,000/mo",
    topPain: "Leads go cold between inspection and estimate. Competitors close first.",
    useCases: [
      {
        id: "roofing-instant-followup",
        title: "Instant Estimate Follow-Up Sequence",
        problem: "After a free inspection, 60% of homeowners ghost. No follow-up system exists.",
        solution: "3-touch automated SMS + email sequence triggered after estimate sent: same day, day 3, day 7. AI personalizes the message with the quote amount and weather data.",
        tools: ["Make", "Twilio", "Claude", "GoHighLevel (GHL)"],
        monthlyValue: "$1,200–$2,000/mo",
        difficulty: "Easy",
        timeToDeliver: "3–5 days",
        pitchLine: "You sent 40 estimates last month and only closed 8. I'll follow up with the other 32 automatically.",
      },
      {
        id: "roofing-storm-alerts",
        title: "Storm Alert Lead Capture",
        problem: "After a hail storm, homeowners Google roofers within 24 hours. They don't have a system to capture them.",
        solution: "Automated weather alert → AI-generated 'storm damage checklist' landing page → SMS follow-up within 60 seconds of opt-in.",
        tools: ["n8n", "Weather API", "Twilio", "GoHighLevel (GHL)"],
        monthlyValue: "$800–$1,500/mo",
        difficulty: "Medium",
        timeToDeliver: "1–2 weeks",
        pitchLine: "The storm that hit last Tuesday generated 200 Google searches in your zip code. How many did you capture?",
      },
      {
        id: "roofing-review-engine",
        title: "Post-Job Review Engine",
        problem: "They do great work but only have 12 Google reviews. Competitors have 300+.",
        solution: "24 hours after job completion, automated SMS requests a review with a direct Google link. Negative feedback captured privately first.",
        tools: ["Make", "Twilio", "Google Business API"],
        monthlyValue: "$400–$600/mo",
        difficulty: "Easy",
        timeToDeliver: "1–2 days",
        pitchLine: "You've done 200 jobs this year and have 12 reviews. Your competitor has 400. Let's fix that this week.",
      },
    ],
  },
  {
    id: "gyms",
    industry: "Gyms & Fitness Studios",
    emoji: "💪",
    description: "High churn, expensive member acquisition, and underused leads from free trials.",
    avgDealSize: "$800–$2,000/mo",
    topPain: "Free trial no-shows and members who ghost after month 2.",
    useCases: [
      {
        id: "gym-trial-conversion",
        title: "Free Trial Conversion Sequence",
        problem: "40% of free trial sign-ups never show up. Of those who do, only 25% convert to paid.",
        solution: "Pre-visit: automated SMS confirmation + what-to-expect video. Post-visit: AI-personalized check-in within 2 hours, 3-day follow-up, 7-day offer.",
        tools: ["Make", "Twilio", "Claude", "GoHighLevel (GHL)"],
        monthlyValue: "$600–$1,200/mo",
        difficulty: "Easy",
        timeToDeliver: "3–5 days",
        pitchLine: "You're spending $80 to acquire each free trial. Right now 75% of them don't convert. I can cut that in half.",
      },
      {
        id: "gym-churn-prediction",
        title: "At-Risk Member Re-Engagement",
        problem: "Members who haven't checked in for 14+ days are 80% likely to cancel. No one reaches out.",
        solution: "Automated attendance tracking triggers a personalized outreach when a member goes dark: AI-written SMS from their trainer with a re-engagement offer.",
        tools: ["n8n", "Mindbody API", "Twilio", "GoHighLevel (GHL)"],
        monthlyValue: "$800–$1,500/mo",
        difficulty: "Medium",
        timeToDeliver: "1–2 weeks",
        pitchLine: "You have 45 members who haven't been in for 3 weeks. By the time they cancel, it's too late. I'll reach them now.",
      },
    ],
  },
  {
    id: "financial-advisors",
    industry: "Financial Advisors",
    emoji: "📈",
    description: "Relationship-driven, compliance-heavy, and entirely dependent on referrals.",
    avgDealSize: "$2,500–$6,000/mo",
    topPain: "Referrals come in irregularly, and there's no system to stay top of mind with prospects.",
    useCases: [
      {
        id: "fa-newsletter-ai",
        title: "AI-Personalized Client Newsletter",
        problem: "Advisors know they should communicate regularly but don't have time. Generic mass emails get ignored.",
        solution: "Monthly AI-generated newsletter personalized by client segment (pre-retiree, business owner, young professional). Relevant market context, personal financial tips, one clear CTA.",
        tools: ["Claude", "Instantly", "Google Sheets"],
        monthlyValue: "$1,500–$2,500/mo",
        difficulty: "Easy",
        timeToDeliver: "5–7 days",
        pitchLine: "Your clients haven't heard from you since December. A competitor is in their inbox every month.",
      },
      {
        id: "fa-lead-qualification",
        title: "AI Prospect Qualification Bot",
        problem: "Every intro call takes 30 minutes. Half the prospects aren't qualified. Associate advisors are stuck on screening calls.",
        solution: "AI chat on website and email pre-qualifies: AUM, timeline, goals, pain points. Qualified leads get booked automatically into GHL calendar; unqualified get a resource and nurture sequence.",
        tools: ["Relevance AI", "GoHighLevel (GHL)", "Make", "Apollo"],
        monthlyValue: "$2,000–$3,500/mo",
        difficulty: "Medium",
        timeToDeliver: "1–2 weeks",
        pitchLine: "Half your intro calls aren't qualified. I'll screen them before they reach your calendar.",
      },
    ],
  },
  {
    id: "property-management",
    industry: "Property Management",
    emoji: "🏢",
    description: "High-volume maintenance requests, tenant turnover costs, and owner communication overhead.",
    avgDealSize: "$1,500–$4,000/mo",
    topPain: "Maintenance tickets fall through the cracks and angry tenants leave bad reviews.",
    useCases: [
      {
        id: "pm-maintenance-triage",
        title: "AI Maintenance Request Triage",
        problem: "Maintenance requests come in via text, email, voicemail, and portal. Staff manually sorts and routes them. Things get missed.",
        solution: "Unified intake → AI classifies urgency (emergency vs. routine), routes to the right vendor, sends tenant an ETA automatically.",
        tools: ["n8n", "Claude", "Twilio", "GoHighLevel (GHL)"],
        monthlyValue: "$1,500–$3,000/mo",
        difficulty: "Medium",
        timeToDeliver: "1–2 weeks",
        pitchLine: "Your maintenance team is spending 3 hours a day sorting requests. I'll automate that and cut your response time in half.",
      },
      {
        id: "pm-tenant-renewal",
        title: "Tenant Renewal Campaign",
        problem: "70% of tenants decide to renew or move 60–90 days before lease end. No one reaches out until 30 days out — too late.",
        solution: "90-day automated renewal campaign: market comparison email → personal check-in SMS → renewal offer with incentive at 60 days.",
        tools: ["Make", "Claude", "Twilio", "GoHighLevel (GHL)"],
        monthlyValue: "$800–$1,500/mo",
        difficulty: "Easy",
        timeToDeliver: "5–7 days",
        pitchLine: "Tenant turnover costs you $2,000+ per unit. I'll start the renewal conversation 90 days before it becomes a problem.",
      },
    ],
  },
  {
    id: "auto-dealerships",
    industry: "Auto Dealerships",
    emoji: "🚗",
    description: "High-ticket inventory, service lane revenue, and recall management — with leads who shop 5 different lots before buying.",
    avgDealSize: "$2,000–$5,000/mo",
    topPain: "Missed service appointments, slow response to online leads, and recall outreach handled manually.",
    useCases: [
      {
        id: "auto-recall-outreach",
        title: "AI Recall Outreach System",
        problem: "The recall list has 300+ customers who legally need service. Nobody is calling them systematically. The service lane is underutilized.",
        solution: "AI voice agent proactively calls previous customers when their recall is due, qualifies the conversation, and books a service appointment. Voicemail drop + email follow-up for non-answers. Every interaction logged to CRM.",
        tools: ["Assistable (voice agent)", "GoHighLevel (GHL)", "Make", "Claude"],
        monthlyValue: "$1,500–$3,000/mo",
        difficulty: "Medium",
        timeToDeliver: "1–2 weeks",
        pitchLine: "Your recall list has 300 customers who legally need service. We'll call all of them automatically and fill your service lane for the next 90 days.",
      },
      {
        id: "auto-speed-to-lead",
        title: "Speed-to-Lead Response System",
        problem: "Internet leads from Cars.com, AutoTrader, and the dealer website go cold in under 5 minutes if not contacted. The average dealership calls back in 3+ hours.",
        solution: "AI agent responds to new internet leads within 60 seconds, qualifies buyer timeline and budget, and books a test drive directly into the salesperson's calendar.",
        tools: ["Vapi", "GoHighLevel (GHL)", "n8n"],
        monthlyValue: "$1,500–$2,500/mo",
        difficulty: "Medium",
        timeToDeliver: "1–2 weeks",
        pitchLine: "You're paying $2,000/month for internet leads and responding in 3 hours. Internet car leads go cold in 5 minutes — we'll respond in 60 seconds, automatically.",
      },
      {
        id: "auto-service-retention",
        title: "Service Lane Retention Campaign",
        problem: "Customers service their car once and never hear from the dealership again. No systematic follow-up for oil changes, tire rotations, or seasonal maintenance.",
        solution: "AI-personalized service reminder campaign: contacts customers 6 months after last visit with maintenance reminder specific to their vehicle and service history. Includes a direct booking link.",
        tools: ["Instantly", "Clay", "GoHighLevel (GHL)", "Claude"],
        monthlyValue: "$800–$1,500/mo",
        difficulty: "Easy",
        timeToDeliver: "5–7 days",
        pitchLine: "You serviced 500 cars last quarter. How many of those customers have heard from you since? One campaign to them fills the service lane for the next 60 days.",
      },
    ],
  },
  {
    id: "agencies",
    industry: "Marketing & Creative Agencies",
    emoji: "📣",
    description: "Content-heavy operations, client-dependent revenue, and teams drowning in production work that AI can accelerate by 5x.",
    avgDealSize: "$2,000–$6,000/mo",
    topPain: "60+ hours per week on content production, manual client reporting, and social media management.",
    useCases: [
      {
        id: "agency-content-engine",
        title: "AI Content Production Engine",
        problem: "Content teams spend 60+ hours per week on research, writing, editing, and scheduling. Output is inconsistent and clients want more.",
        solution: "End-to-end AI content pipeline: research brief → Claude outline → full draft → human edit → scheduled publish. Airtable tracks all content across all clients. One workflow serves all clients.",
        tools: ["Claude", "Make", "Airtable", "Buffer"],
        monthlyValue: "$2,000–$4,000/mo",
        difficulty: "Medium",
        timeToDeliver: "1–2 weeks",
        pitchLine: "Your content team is spending 60 hours a week creating content. I'll cut that to 15 without losing quality — and your output volume will double.",
      },
      {
        id: "agency-reporting-automation",
        title: "Automated Client Reporting System",
        problem: "Account managers spend 8–12 hours per month manually pulling data from ad accounts, social platforms, and analytics tools to build client reports.",
        solution: "n8n workflow auto-pulls data from all platforms on a schedule, Claude generates the narrative insights, and the finished report lands in the client's inbox automatically.",
        tools: ["n8n", "Claude", "Google Sheets", "Airtable"],
        monthlyValue: "$1,500–$3,000/mo",
        difficulty: "Medium",
        timeToDeliver: "1–2 weeks",
        pitchLine: "Your account managers spend half a day per client per month on reports. I'll automate that so they can spend that time on strategy instead.",
      },
      {
        id: "agency-linkedin-ghostwriting",
        title: "Executive LinkedIn Ghostwriting",
        problem: "Agency clients know they should be active on LinkedIn but never do it consistently. The work falls to the agency and it's time-consuming.",
        solution: "Claude Projects trained on the executive's voice (from 30+ past posts and transcripts). Produces 5 posts per week that sound exactly like them. 30 minutes of executive time per month — they review and approve.",
        tools: ["Claude Projects", "Buffer", "Notion", "Granola"],
        monthlyValue: "$2,000–$3,500/mo",
        difficulty: "Easy",
        timeToDeliver: "5–7 days",
        pitchLine: "Your CEO hasn't posted on LinkedIn in 6 months. Their top competitor posts every week. Give me 30 minutes of their time per month and I'll handle the rest.",
      },
    ],
  },
]
